steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.job'
      - '-t'
      - 'us-east1-docker.pkg.dev/asheville-ai-agentic-automate/cloud-run-source-deploy/agency-pipeline:latest'
      - '.'
images:
  - 'us-east1-docker.pkg.dev/asheville-ai-agentic-automate/cloud-run-source-deploy/agency-pipeline:latest'
